development:
  adapter: postgresql
  database: weird-stuff_dev
  host: localhost

test:
  adapter: postgresql
  database: weird-stuff_test
  host: localhost

production:
  adapter: postgresql
  database: weird-stuff_production
  host: localhost
